### ISSUE TITLE
Associate credit card to existing customer

### ISSUE THREAD

**Issue by moisesnarvaez** [epayco/epayco-ruby#2]
It is possible to associate a Credit card token to an existing customer?
I want to give to the user the option to have multiple credit cards and choose one.

**Comment by pruebasepayco** [comment]
hi.

for the moment is not possible, because of customer objet is make whit the token id  like this:
customer_info = {
  token_card: "eXj5Wdqgj7xzvC7AR",
  name: "Joe Doe",
  email: "joe@payco.co",
  phone: "3005234321",
  default: true
}
so, you have to save the data of name, email, phone, when the customer selec the credit card that it is selected the system send the data like name, email, phone, and create a new customer,this is a suggest

**Comment by pruebasepayco** [comment]
hi,

nice to know about you request, yes you can make some different tokens and then you might to create a new customer and associate it the token created, this is the way to associate to credit card token to a customer, using the same method to create a customer,that search in data base, and findthat is already created user with the same data and assign the new token
